vich_uploader:
  db_driver: orm
  mappings:
    posts:
      uri_prefix: /src/posts
      upload_destination: '%kernel.project_dir%/public/src/posts'
      namer: App\Naming\SlugUsingNamer
    products:
      uri_prefix: /src/products
      upload_destination: '%kernel.project_dir%/public/src/products'
      namer: App\Naming\SlugUsingNamer